// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBypassChange();

int pl1;
int pl2;
int pl3;
int pl4;
bool bypass;

void initProperties(){

  ArduinoCloud.addProperty(pl1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pl2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pl3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pl4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(bypass, READWRITE, ON_CHANGE, onBypassChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);